name: ci_cmake

env:
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"

jobs:

  core:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    env:
      FC: gfortran-12

    steps:
    - uses: actions/checkout@v4

    - run: cmake --preset default

    - run: cmake --build --preset default

    - run: ctest --preset default -LE python
